baseURL: "https://xinjiangshao.com/"
title: Xinjiang Shao
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-66561519-1

minify:
  disableXML: true
  minifyOutput: true

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary


params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Xinjiang Shao
  description: "Xinjiang Shao is a Senior Software Enigneer living in Chicago, IL"
  keywords: [Blog, Portfolio, Software Engineer]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["https://xinjiangshao.com/photo-of-xinjiang.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/logo-high-resolution.png"
    favicon16x16: "/logo-high-resolution.png"
    favicon32x32: "/logo-high-resolution.png"
    apple_touch_icon: "/logo-high-resolution.png"
    safari_pinned_tab: "/logo-high-resolution.png"

  label:
    text: "Home"
    icon: /logo-high-resolution.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Xinjiang Shao"
    subtitle: "Xinjiang Shao is a Senior Software Enigneer living in Chicago, IL"
    imageUrl: "/profile_square.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Archive
        url: "/archives/"
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: "Xinjiang Shao is currently working as a Senior Software engineer at Peapod Digital Labs, previously he was at Peapod and EXACT Sports, and he was on the team of building PrepHero. The dude who works as a software engineer, dreams about being a chef, and tries to design pleasant things. While I'm not coding, I like reading as often as possible, writing occasionally, drawing randomly, cooking creatively, running regularly."

  socialIcons:
    - name: twitter
      url: "https://twitter.com/soleoshao"
    - name: github
      url: "https://github.com/soleo"
    - name: instagram
      url: "https://www.instagram.com/soleoshao/"
    - name: linkedin
      url: "https://www.linkedin.com/in/xinjiangshao/"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page
    responsiveImages: true
    linkFullImages: true

  editPost:
    URL: "https://github.com/soleo/xinjiangshao.com/edit/master/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: posts
      name: POSTS
      url: /posts/
      weight: 10
    - identifier: tags
      name: TAGS
      url: /tags/
      weight: 20
    - identifier: search
      name: SEARCH
      url: /search/
      weight: 21
    - identifier: about
      name: ABOUT ME
      url: /about/
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai