baseURL: "https://xinjiangshao.com/"
title: Xinjiang Shao
paginate: 5
theme:
- PaperMod
- "hugo-shortcode-gallery"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-66561519-1

minify:
  disableXML: true
  minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
          main:
            - identifier: blog
              name: Blog
              url: /archives/
              weight: 10
            - identifier: photography
              name: Photography
              url: /photography/best-of-a-decade/
              weight: 11
            - identifier: search
              name: Search
              url: /search/
              weight: 21
            - identifier: about
              name: About
              url: /about/
              weight: 30
    zh:
        languageName: ":zh:"
        languageAltTitle: Chinese
        weight: 2
        title: PaperModL2
        taxonomies:
          category: ZHcategories
          tag: ZHtags
          series: ZHseries
        menu:
          main:
            - identifier: blog
              name: 日志
              url: /archives/
              weight: 10
            - identifier: photography
              name: 摄影
              url: /photography/best-of-a-decade/
              weight: 11
            - identifier: search
              name: 搜索
              url: /search/
              weight: 21
            - identifier: about
              name: 关于
              url: /about/
              weight: 30
        profileMode:
          enabled: true # needs to be explicitly set
          title: "邵新江"
          subtitle: "热爱做菜·旅行·认识世界的软件工程师"
          imageUrl: "profile_xinjiang.png"
          imageWidth: 300
          imageHeight: 300
          imageTitle: 邵新江

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary


params:
  galleryRowHeight    : 200
  galleryMargins      : 10
  galleryResizeOptions: "800x800 q88 Lanczos"
  galleryPreviewType  : "blur"
  galleryThumbnailHoverEffect : "enlarge"
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Xinjiang Shao
  description: "Coding by day, conjuring culinary creations by night, Xinjiang Shao is a software engineer who fuels his creativity with an eye for design and a passion for cooking. In his free time, he brings his dreams to life in the kitchen, crafting delicious dishes and seeking out new and imaginative ways to design pleasant things."
  keywords: [Blog, Portfolio, Software Engineer]
  author: "Xinjiang Shao"
  # author: ["Me", "You"] # multiple authors
  images: ["/profile_xinjiang.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/logo-high-resolution.png"
    favicon16x16: "/logo-high-resolution.png"
    favicon32x32: "/logo-high-resolution.png"
    apple_touch_icon: "/logo-high-resolution.png"
    safari_pinned_tab: "/logo-high-resolution.png"

  label:
    text: "Xinjiang S."
    icon: /logo-high-resolution.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Xinjiang Shao"
    subtitle: "Software engineer by day, aspiring chef by night. Fueled by a passion for design and cooking, Xinjiang Shao creates and designs both code and cuisine."
    imageUrl: "profile_xinjiang.png"
    imageWidth: 300
    imageHeight: 300
    imageTitle: Xinjiang Shao
    buttons:
      - name: Tags
        url: tags
      - name: Slides
        url: https://slides.com/xinjiangshao
      - name: Newsletter
        url: https://soleo.substack.com/

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: "Coding by day, conjuring culinary creations by night, Xinjiang Shao is a software engineer who fuels his creativity with an eye for design and a passion for cooking. In his free time, he brings his dreams to life in the kitchen, crafting delicious dishes and seeking out new and imaginative ways to design pleasant things."

  socialIcons:
    - name: twitter
      url: "https://twitter.com/soleoshao"
    - name: github
      url: "https://github.com/soleo"
    - name: instagram
      url: "https://www.instagram.com/soleoshao/"
    - name: linkedin
      url: "https://www.linkedin.com/in/xinjiangshao/"
    - name: youtube
      url: "https://www.youtube.com/xinjiangshao"
    - name: buymeacoffee
      url: "https://www.buymeacoffee.com/soleo"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page
    responsiveImages: true
    linkFullImages: true

  editPost:
    URL: "https://github.com/soleo/xinjiangshao.com/edit/master/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: blog
      name: Blog
      url: /archives/
      weight: 10
    - identifier: photography
      name: Photography
      url: /photography/best-of-a-decade/
      weight: 11
    - identifier: search
      name: Search
      url: /search/
      weight: 21
    - identifier: about
      name: About
      url: /about/
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai

imaging.exif:
    includeFields : ".*"